feat: create site and configure option in erpnext stack

diff --git a/compose/erpnext.yml b/compose/erpnext.yml
--- a/compose/erpnext.yml
+++ b/compose/erpnext.yml
@@ -239,8 +239,73 @@ services:
       - bench-network
       - mariadb-network
 
+  configurator:
+    <<: *custom_image
+    deploy:
+      mode: replicated
+      replicas: ${CONFIGURE:-0}
+      restart_policy:
+        condition: none
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+    entrypoint: ["bash", "-c"]
+    command:
+      - >
+        bench set-config -g db_host $$DB_HOST;
+        bench set-config -gp db_port $$DB_PORT;
+        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
+        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
+        bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO";
+        bench set-config -gp socketio_port $$SOCKETIO_PORT;
+    environment:
+      DB_HOST: ${DB_HOST:-mariadb_db}
+      DB_PORT: ${DB_PORT:-3306}
+      REDIS_CACHE: redis-cache:6379
+      REDIS_QUEUE: redis-queue:6379
+      REDIS_SOCKETIO: redis-socketio:6379
+      SOCKETIO_PORT: 9000
+
+  create-site:
+    <<: *custom_image
+    deploy:
+      mode: replicated
+      replicas: ${CREATE_SITE:-0}
+      restart_policy:
+        condition: none
+    entrypoint: ["bash", "-c"]
+    command:
+      - >
+        wait-for-it -t 120 $$DB_HOST:$$DB_PORT;
+        wait-for-it -t 120 redis-cache:6379;
+        wait-for-it -t 120 redis-queue:6379;
+        export start=`date +%s`;
+        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+        do
+          echo "Waiting for sites/common_site_config.json to be created";
+          sleep 5;
+          if (( `date +%s`-start > 120 )); then
+            echo "could not find sites/common_site_config.json with required keys";
+            exit 1
+          fi
+        done;
+        echo "sites/common_site_config.json found";
+        [[ -d "sites/${SITE_NAME}" ]] && echo "${SITE_NAME} already exists" && exit 0;
+        bench new-site --mariadb-user-host-login-scope='%' --admin-password=$${ADMIN_PASSWORD} --db-root-username=root --db-root-password=$${DB_ROOT_PASSWORD} $${INSTALL_APP_ARGS} $${SITE_NAME};
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+    environment:
+      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
+      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
+      INSTALL_APP_ARGS: ${INSTALL_APP_ARGS}
+      SITE_NAME: ${SITE_NAME}
+    networks:
+      - bench-network
+      - mariadb-network
+
   redis-cache:
-    image: redis:6.2-alpine
+    image: redis:7-alpine
     deploy:
       restart_policy:
         condition: on-failure
@@ -256,7 +321,7 @@ services:
       retries: 3
 
   redis-queue:
-    image: redis:6.2-alpine
+    image: redis:7-alpine
     deploy:
       restart_policy:
         condition: on-failure
@@ -274,7 +339,7 @@ services:
       retries: 3
 
   redis-socketio:
-    image: redis:6.2-alpine
+    image: redis:7-alpine
     deploy:
       restart_policy:
         condition: on-failure
@@ -322,6 +387,8 @@ networks:
 # BENCH_NAME              | Name of the bench newtork            | erpnext
 # IMAGE_NAME              | Container image to use               | docker.io/frappe/erpnext
 # MIGRATE                 | Enable migration on deploy           | 1
+# CONFIGURE               | Re-generate common_site_config.json  | 0
+# CREATE_SITE             | Enable site creation on deploy       | 0
 # RESTIC_PASSWORD         | Restic Password. DO NOT Forget!      | nil
 # RESTIC_REPOSITORY       | Path Styled S3 endpoint              | nil
 # SITES                   | Mandatory List of sites as back      | nil
